language: python
install:
  - pip install -r dev-requirements.txt

before_script:
  - zerodb-manage init_db --username root --passphrase test --sock localhost:8001
  - zerodb-server &

python:
  - "2.7"
 
script: "python test.py"
